// 장르 대분류 → 소분류 데이터
// Suno v5.5가 인식하는 장르명 기준, 영문으로 표기

export interface GenreCategory {
  id: string;
  label: string;
  options: string[];
}

export const GENRE_CATEGORIES: GenreCategory[] = [
  {
    id: "pop",
    label: "팝/댄스",
    options: [
      "K-Pop", "J-Pop", "C-Pop", "Pop", "Dance Pop", "Synth Pop", "Electro Pop",
      "City Pop", "Bubblegum Pop", "Teen Pop", "Indie Pop", "Art Pop",
      "Power Pop", "Baroque Pop", "Dream Pop", "Noise Pop", "Chamber Pop",
      "Sophisti-Pop", "Euro Pop", "Latin Pop",
    ],
  },
  {
    id: "rnb",
    label: "R&B/소울",
    options: [
      "R&B", "Neo Soul", "Soul", "Gospel", "Motown", "Quiet Storm",
      "Contemporary R&B", "Alternative R&B", "PBR&B", "Funk",
      "P-Funk", "Disco", "Nu Disco", "Boogie",
    ],
  },
  {
    id: "hiphop",
    label: "힙합/랩",
    options: [
      "Hip-Hop", "Trap", "Boom Bap", "Cloud Rap", "Drill", "UK Drill",
      "Mumble Rap", "Conscious Rap", "Gangsta Rap", "Emo Rap",
      "Lo-Fi Hip-Hop", "Jazz Rap", "Phonk", "Old School Hip-Hop",
      "K-Hip-Hop", "Crunk", "Grime", "Trip-Hop",
    ],
  },
  {
    id: "rock",
    label: "록/메탈",
    options: [
      "Rock", "Alt Rock", "Indie Rock", "Punk Rock", "Post Punk",
      "Metal", "Heavy Metal", "Nu Metal", "Progressive Rock", "Prog Metal",
      "Garage Rock", "Grunge", "Psychedelic Rock", "Stoner Rock",
      "Shoegaze", "Post-Rock", "Math Rock", "Emo", "Pop Punk",
      "Hardcore", "Metalcore", "Deathcore", "Black Metal", "Death Metal",
      "Doom Metal", "Thrash Metal", "Power Metal", "Symphonic Metal",
      "Folk Rock", "Blues Rock", "Southern Rock", "Surf Rock",
      "Britpop", "Madchester", "New Wave", "Gothic Rock",
    ],
  },
  {
    id: "electronic",
    label: "일렉트로닉",
    options: [
      "EDM", "House", "Deep House", "Tech House", "Progressive House",
      "Tropical House", "Future House", "Acid House",
      "Techno", "Minimal Techno", "Detroit Techno", "Industrial Techno",
      "Trance", "Psytrance", "Progressive Trance", "Uplifting Trance",
      "Dubstep", "Riddim", "Brostep",
      "Drum & Bass", "Liquid DnB", "Neurofunk", "Jungle",
      "Ambient", "Dark Ambient", "Ambient House",
      "Synthwave", "Retrowave", "Vaporwave", "Future Funk",
      "IDM", "Glitch", "Breakbeat", "UK Garage", "2-Step",
      "Hardstyle", "Hardcore", "Gabber", "Happy Hardcore",
      "Chillwave", "Chillstep", "Downtempo", "Electronica",
      "Hyperpop", "PC Music", "Deconstructed Club",
      "Future Bass", "Future Garage", "Wave",
      "Electro Swing", "Nu Jazz",
    ],
  },
  {
    id: "acoustic",
    label: "감성/어쿠스틱",
    options: [
      "Ballad", "Lo-Fi", "Lo-Fi Beats", "Acoustic", "Folk",
      "Singer-Songwriter", "Soft Rock", "Adult Contemporary",
      "Coffeehouse", "Unplugged", "Americana", "Country",
      "Country Pop", "Bluegrass", "Neo-Folk", "Anti-Folk",
      "Bedroom Pop", "Chill Pop", "Sad Pop",
    ],
  },
  {
    id: "jazz_blues",
    label: "재즈/블루스",
    options: [
      "Jazz", "Smooth Jazz", "Cool Jazz", "Bebop", "Free Jazz",
      "Jazz Fusion", "Acid Jazz", "Modal Jazz", "Swing",
      "Big Band", "Bossa Nova", "Latin Jazz",
      "Blues", "Delta Blues", "Chicago Blues", "Electric Blues",
      "Soul Blues", "Blues Rock",
    ],
  },
  {
    id: "world",
    label: "월드/전통",
    options: [
      "Reggae", "Dancehall", "Dub", "Ska", "Rocksteady",
      "Latin", "Salsa", "Reggaeton", "Dembow", "Bachata", "Cumbia",
      "Afrobeat", "Afropop", "Amapiano", "Highlife",
      "Flamenco", "Fado", "Celtic", "Polka",
      "Bollywood", "Qawwali", "Bhangra",
      "K-Trad Fusion", "Trot", "Enka",
      "Middle Eastern", "Turkish Pop", "Arabic Pop",
      "Caribbean", "Soca", "Calypso", "Zouk",
      "Bossa Nova", "MPB", "Samba", "Forró",
    ],
  },
  {
    id: "cinematic",
    label: "시네마틱/클래식",
    options: [
      "Cinematic", "Epic", "Orchestral", "Film Score", "Soundtrack",
      "Trailer Music", "Dark Cinematic",
      "Classical", "Baroque", "Romantic", "Contemporary Classical",
      "Minimalist", "Post-Classical", "Neoclassical",
      "New Age", "Meditation", "Spa Music",
      "Video Game Music", "Chiptune", "8-Bit",
    ],
  },
  {
    id: "experimental",
    label: "실험/아방가르드",
    options: [
      "Experimental", "Avant-Garde", "Noise", "Industrial",
      "Art Rock", "Art Pop", "Krautrock",
      "Musique Concrète", "Drone", "Microtonal",
      "Sound Design", "Field Recording", "Generative",
      "Spoken Word", "Poetry Slam",
    ],
  },
  {
    id: "kids_holiday",
    label: "키즈/시즌",
    options: [
      "Children's Music", "Lullaby", "Nursery Rhyme",
      "Christmas", "Holiday", "Halloween",
      "Wedding Music", "Graduation",
      "Worship", "Hymn", "CCM",
    ],
  },
];

// 전체 장르 수 계산용
export const TOTAL_GENRE_COUNT = GENRE_CATEGORIES.reduce((sum, cat) => sum + cat.options.length, 0);

// 장르 설명 툴팁
export const GENRE_DESCRIPTIONS: Record<string, string> = {
  "K-Pop": "한국 팝. 중독적 훅, 칼군무 대응 리듬, 한영 믹스 가사",
  "J-Pop": "일본 팝. 밝은 멜로디, 복잡한 코드 진행, 아니메/드라마 감성",
  "Pop": "대중 팝. 캐치한 멜로디, 라디오 친화적, 보편적 감정",
  "Dance Pop": "댄스 팝. 클럽 리듬 + 팝 멜로디, 에너지틱한 코러스",
  "Synth Pop": "신스 팝. 80s 신디사이저 중심, 전자적 멜로디",
  "City Pop": "시티 팝. 80s 일본 팝, 레트로 그루브, 도시적 세련미",
  "Dream Pop": "드림 팝. 몽환적 리버브, 부드러운 보컬, 에테리얼한 질감",
  "R&B": "리듬 앤 블루스. 그루비한 리듬, 감성적 보컬, 소울풀한 멜로디",
  "Neo Soul": "네오 소울. 재즈 화성 + R&B 그루브, 유기적이고 따뜻한 사운드",
  "Soul": "소울. 감정적 보컬 전달력, 가스펠 영향, 깊은 그루브",
  "Gospel": "가스펠. 교회 음악, 합창 하모니, 영적 고양감",
  "Funk": "펑크. 그루비한 베이스라인, 리듬 중심, 몸이 움직이는 음악",
  "Disco": "디스코. 4-on-the-floor 킥, 화려한 스트링, 댄스플로어 에너지",
  "Hip-Hop": "힙합. 비트 + 라임 + 메시지, 808 베이스, 스트리트 문화",
  "Trap": "트랩. 808 서브베이스, 빠른 하이햇 롤, 어두운 분위기",
  "Boom Bap": "붐뱁. 올드스쿨 힙합, 강한 킥스네어, 소울 샘플링",
  "Drill": "드릴. 슬라이딩 808, 어두운 분위기, 공격적 플로우",
  "Emo Rap": "이모 랩. 감정적 가사, 멜로딕 랩, 우울한 분위기",
  "Phonk": "퐁크. 멤피스 랩 샘플 + 카우벨, 어둡고 중독적인 그루브",
  "Grime": "그라임. UK 언더그라운드, 빠른 BPM, 공격적 MC",
  "Trip-Hop": "트립합. 느린 비트, 몽환적 분위기, 다운템포 일렉트로닉",
  "Rock": "록. 일렉트릭 기타 중심, 강렬한 에너지, 라이브 밴드 사운드",
  "Indie Rock": "인디 록. 독립적 사운드, 실험적 편곡, 개성 있는 톤",
  "Punk Rock": "펑크 록. 빠르고 거친 에너지, 반항적, DIY 정신",
  "Metal": "메탈. 헤비 디스토션, 더블 킥, 공격적 리프",
  "Grunge": "그런지. 90s 시애틀, 거칠고 우울한 기타, 투박한 에너지",
  "Shoegaze": "슈게이즈. 벽 같은 기타 리버브, 몽환적, 보컬이 묻힘",
  "Post-Rock": "포스트 록. 서서히 빌드업, 기악 중심, 시네마틱 감정선",
  "EDM": "EDM. 빌드업→드롭 구조, 고에너지, 클럽/페스티벌 사운드",
  "House": "하우스. 4-on-the-floor 킥, 따뜻한 베이스, 그루비 루프",
  "Deep House": "딥 하우스. 따뜻한 패드, 소울풀한 보컬 샘플, 깊은 베이스",
  "Afro House": "아프로 하우스. 아프리카 퍼커션 + 하우스 킥, 트라이벌 그루브",
  "UK Garage": "UK 개러지. 2스텝 리듬, 쵸핑된 보컬, 셔플 그루브",
  "Techno": "테크노. 기계적 반복, 최면적 루프, 인더스트리얼 텍스처",
  "Trance": "트랜스. 몽환적 멜로디, 에너지 빌드업, 유포릭한 피크",
  "Dubstep": "덥스텝. 무거운 우블 베이스, 하프타임 리듬, 공격적 드롭",
  "Drum & Bass": "드럼 앤 베이스. 빠른 브레이크비트, 딥 베이스, 160+ BPM",
  "Ambient": "앰비언트. 리듬 없는 텍스처, 공간감, 명상적 분위기",
  "Synthwave": "신스웨이브. 80s 레트로 신스, 네온 감성, 노스탤지어",
  "Hyperpop": "하이퍼팝. 과장된 프로덕션, 디스토션 보컬, 장르 파괴",
  "Ballad": "발라드. 감정적 서사, 피아노/스트링, 느린 템포",
  "Lo-Fi": "로파이. 테이프 새추레이션, 재지한 코드, 편안한 비트",
  "Acoustic": "어쿠스틱. 자연 악기, 따뜻한 톤, 친밀한 녹음",
  "Folk": "포크. 스토리텔링, 어쿠스틱 기타, 어시 감성",
  "Country": "컨트리. 미국 남부, 기타/밴조, 서사적 가사",
  "Jazz": "재즈. 복잡한 화성, 스윙 리듬, 즉흥 연주",
  "Blues": "블루스. 12마디 진행, 기타 벤딩, 깊은 감정",
  "Bossa Nova": "보사노바. 브라질, 부드러운 리듬, 나일론 기타",
  "Reggae": "레게. 오프비트 기타, 원드롭 리듬, 자메이카 뿌리",
  "Latin": "라틴. 클라베 리듬, 퍼커션 중심, 열정적 에너지",
  "Afrobeat": "아프로비트. 서아프리카 리듬, 폴리리듬, 큰 앙상블",
  "Amapiano": "아마피아노. 남아공, 로그 드럼, 셔플 베이스",
  "Reggaeton": "레게톤. 뎀보우 리듬, 라틴 팝, 클럽 에너지",
  "Trot": "트로트. 한국 전통 팝, 꺾기 창법, 2/4 바운스",
  "Cinematic": "시네마틱. 오케스트라, 에픽 스케일, 영화적 감정선",
  "Classical": "클래식. 정통 서양 고전음악, 오케스트라 편성",
  "Orchestral": "오케스트라. 풀 앙상블, 교향곡적 스케일",
  "Worship": "워십. 현대 예배 음악, 감정적 고양, 밴드 편성",
  "CCM": "CCM. 기독교 현대 음악, 팝/록 기반 찬양",
  "Cloud Rap": "클라우드 랩. 몽환적 비트, 느린 플로우, 에테리얼한 분위기",
  "UK Drill": "UK 드릴. 슬라이딩 808, 런던 스타일, 어두운 에너지",
  "Mumble Rap": "멈블 랩. 불명확한 발음, 멜로딕 플로우, 트랩 비트",
  "Conscious Rap": "컨셔스 랩. 사회적 메시지, 서사 중심, 깊은 가사",
  "Gangsta Rap": "갱스타 랩. 거리 서사, 공격적 딜리버리, 하드코어",
  "Lo-Fi Hip-Hop": "로파이 힙합. 테이프 새추레이션, 재지 비트, 칠한 분위기",
  "Jazz Rap": "재즈 랩. 재즈 샘플링, 복잡한 화성, 지적인 플로우",
  "Old School Hip-Hop": "올드스쿨 힙합. 80~90s, 클래식 브레이크비트, 원초적 에너지",
  "K-Hip-Hop": "K-힙합. 한국 힙합, 한국어 라임, 로컬 감성",
  "Crunk": "크렁크. 남부 힙합, 에너지틱, 챈트 훅, 파티 음악",
  "Indie Pop": "인디 팝. 독립 레이블, 개성 있는 멜로디",
  "Noise Pop": "노이즈 팝. 노이즈 기타 + 팝 멜로디",
  "Power Pop": "파워 팝. 강렬한 기타 + 캐치한 코러스",
  "PBR&B": "PBR&B. 인디 감성 R&B, 실험적 프로덕션",
  "Alternative R&B": "얼터너티브 R&B. 전통 R&B 벗어난 실험적 접근",
  "Contemporary R&B": "컨템포러리 R&B. 현대적 프로덕션, 세련된 사운드",
  "Nu Disco": "뉴 디스코. 현대적 디스코 리바이벌, 펑키 그루브",
  "Boogie": "부기. 80s 펑크/디스코, 그루비한 베이스라인",
  "P-Funk": "P-펑크. Parliament-Funkadelic 스타일, 우주적 펑크",
  "Motown": "모타운. 60s 소울, 클래식 R&B, 따뜻한 편곡",
  "Quiet Storm": "콰이엇 스톰. 부드러운 R&B, 로맨틱, 밤 분위기",
  "Post Punk": "포스트 펑크. 펑크 이후, 실험적, 어둡고 앵귤러",
  "Psytrance": "사이트랜스. 사이키델릭 트랜스, 고에너지, 환각적",
  "Liquid DnB": "리퀴드 DnB. 부드러운 드럼앤베이스, 소울풀, 멜로딕",
  "Neurofunk": "뉴로펑크. 어둡고 공격적인 DnB, 복잡한 베이스 디자인",
  "Riddim": "리딤. 미니멀 덥스텝, 반복적 우블 베이스",
  "Hardstyle": "하드스타일. 강한 킥, 150+ BPM, 유포릭 멜로디",
  "Future Bass": "퓨처 베이스. 따뜻한 신스, 사이드체인, 감정적 드롭",
  "Vaporwave": "베이퍼웨이브. 80~90s 샘플 왜곡, 초현실적, 느린 템포",
  "Chillwave": "칠웨이브. 몽환적, 로파이, 여름 바이브",
  "IDM": "IDM. 복잡한 리듬, 실험적 전자음악, 지적 댄스",
};
